### ISSUE TITLE
We are generating .reconnes-agent.yaml config but we are trying to read .rwrapper.yaml

### ISSUE THREAD

**Issue by gorums** [hiddengearz/reconness-universal-wrapper#1]
https://github.com/hiddengearz/reconness-universal-wrapper/blob/5e9fd76afed584a2951e4ca041411c32742ef18d/cmd/root.go#L73

https://github.com/hiddengearz/reconness-universal-wrapper/blob/5e9fd76afed584a2951e4ca041411c32742ef18d/cmd/exec.go#L39

**Comment by hiddengearz** [comment]
Good spot, forgot to push this over the weekend. Fixed in 8dd93a593ee50c4441cf4a7bfef43f984ed01ebc
