### ISSUE TITLE
I have my server running on port 80 HTTP not HTTPS/443

### ISSUE THREAD

**Issue by gorums** [hiddengearz/reconness-universal-wrapper#2]
https://github.com/hiddengearz/reconness-universal-wrapper/blob/5e9fd76afed584a2951e4ca041411c32742ef18d/cmd/exec.go#L49

**Comment by gorums** [comment]
Maybe is better if I acn specific my Absolute domain
-s [http|https]://myserver.com:myport

**Comment by hiddengearz** [comment]
Smart idea! Add in 760481bcc8bd6ecc84178759b3a8c3d7d673aeca

You now have to provide the full url e.g `-s https://mydomain.com:8080`
